### ISSUE TITLE
A bit too minimalistic...

### ISSUE THREAD

**Issue by hiwye** [tillsanders/botox#1]
Your CMS might be a bit too minimalistic at this point... :smile: Any plans?

**Comment by hiwye** [comment]
Leave a comment

**Comment by tillsanders** [comment]
Now you say it ;) It's still work in progress. Other things are more important at the moment, but I hope to get back to this in the next few months.

**Comment by hiwye** [comment]
Take your time. I like minimalism haha.

P.S. Just needed to get this out of my open issues. ;)


--
Sebastian Walker
Mercystraße 13
79100 Freiburg
Deutschland

walkermedia Webservices
http://sebastianwalker.org

2016-06-28 21:31 GMT+02:00 Till Sanders <notifications@github.com>:
